[package]
name = "burxt"
version = "0.0.146"
edition = "2021"
description = "The Burxt programming language: typed, compiled, native, exact decimals by default."
license = "MIT OR Apache-2.0"
repository = "https://github.com/andrecorugda/burxt"
readme = "README.md"

[[bin]]
name = "burxt"
path = "src/main.rs"

[dependencies]
inkwell = { version = "0.9.0", features = ["llvm18-1"] }
