#!/usr/bin/env python3
"""Generate docs/reference/ by READING the compiler and the standard library.

    python3 scripts/site-reference.py            # writes docs/reference/ and the search index
    python3 scripts/site-reference.py --check    # exits 1 if anything on disk is out of date

The reference this replaces was one hand-written page, and it had already rotted: it listed `record`
as a keyword eleven versions after the language renamed it to `class`, and it called `for` and `is`
"reserved but not yet used" ninety versions after `for x in xs` shipped. Its own header said
"generated by reading the compiler, not by memory", which was true of the afternoon it was written
and of no afternoon since.

So this reads the compiler. Four sources, none of them a list kept here:

  * `src/rust-compiler/lexer.rs` — the keyword table (`"word" => Token::…`) and `renamed_keyword`, which is where
    the eight spellings that no longer compile live along with what each became.
  * `src/rust-compiler/typeck.rs` — `is_reserved_name` for the names a program may not declare, and the
    builtin→effect table for which of them reach the world.
  * `src/rust-compiler/main.rs` — the usage block, which is the whole command-line surface. Two of those commands,
    `review` and `mcp-schema`, are the most distinctive things in the language and were documented
    nowhere on the site.
  * `lib/*.bx` — every standard-library declaration, with the `//` prose already written above it.

What is NOT scraped is each builtin's signature, because the typechecker states those in arity
errors that carry `{}` placeholders and read as apologies rather than as declarations. Those are
written out below — and then VERIFIED by compiling a real use of each one. A wrong signature here
does not ship: the probe fails and this script exits non-zero naming the builtin. Every refusal
quoted on the page is likewise captured by running the compiler, never typed.

And the two lists are checked against each other. A builtin the compiler reserves and this file has
no entry for is an error, so adding one to the language makes this fail until the reference knows
about it.
"""
import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile


def _sibling(name):
    """Import a script that sits next to this one, hyphen in its name and all."""
    # Without this the import leaves a `scripts/__pycache__` behind. It is git-ignored, so nothing
    # breaks — but a generator that litters the tree it generates from is a generator someone will
    # eventually commit the litter of.
    sys.dont_write_bytecode = True
    here = os.path.dirname(os.path.abspath(__file__))
    spec = importlib.util.spec_from_file_location(
        name.replace("-", "_"), os.path.join(here, name + ".py")
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# The sidebar generator owns the one rule for what id a heading carries: it prefers a `{: #…}` the
# page states outright and falls back to kramdown's slug. The search index has to agree with the
# sidebar exactly — two rules would mean the sidebar and the search box disagreeing about where a
# section is, and both would look like they worked.
nav = _sibling("site-nav")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# `BURXT` in the environment wins, so the test suite can hand over whatever profile cargo built.
# Falling back to the release build is right for a human typing this by hand. The same lesson
# site-examples.py records: a release-only default meant this silently skipped in CI, which builds
# debug, for thirteen versions.
BURXT = os.environ.get("BURXT") or os.path.join(ROOT, "target", "release", "burxt")
OUT = os.path.join(ROOT, "docs", "reference")
SEARCH = os.path.join(ROOT, "docs", "assets", "search.json")
GH = "https://github.com/andrecorugda/burxt/blob/main"

# The standard library, in reading order rather than alphabetical: absence before failure, and the
# containers after the pieces they are built from.
MODULES = ["option", "result", "string", "map", "json", "files", "os"]


def read(*parts):
    with open(os.path.join(ROOT, *parts)) as f:
        return f.read()


# ---------------------------------------------------------------------------------------------
# What the compiler knows
# ---------------------------------------------------------------------------------------------

def keywords():
    """The keyword table, from `"word" => Token::Variant` in src/rust-compiler/lexer.rs."""
    found = []
    for line in read("src", "rust-compiler", "lexer.rs").splitlines():
        m = re.match(r'^\s*"([A-Za-z_]+)"\s*=>\s*Token::', line)
        if m:
            found.append(m.group(1))
    if len(found) < 20:
        sys.exit("could not read the keyword table out of src/rust-compiler/lexer.rs — it moved")
    return found


def renamed():
    """The spellings that no longer compile, and what each became, from `renamed_keyword`."""
    body = read("src", "rust-compiler", "lexer.rs").split("fn renamed_keyword", 1)[1].split("_ => return None", 1)[0]
    pairs = []
    # `"fn" => ("function", "…")` on one line, and the multi-line form where the tuple wraps.
    for m in re.finditer(r'"([a-z]+)"\s*=>\s*\(\s*\n?\s*"([a-z]+)"', body):
        pairs.append((m.group(1), m.group(2)))
    if len(pairs) < 6:
        sys.exit("could not read `renamed_keyword` out of src/rust-compiler/lexer.rs — it moved")
    return pairs


def reserved():
    """The names a program may not declare, from `is_reserved_name` in src/rust-compiler/typeck.rs."""
    body = read("src", "rust-compiler", "typeck.rs").split("fn is_reserved_name", 1)[1].split("}", 1)[0]
    found = [w for w in re.findall(r'"([a-z_]+)"', body)]
    if len(found) < 10:
        sys.exit("could not read `is_reserved_name` out of src/rust-compiler/typeck.rs — it moved")
    return found


def builtin_effects():
    """Which builtins reach the world, from the effect table in src/rust-compiler/typeck.rs."""
    text = read("src", "rust-compiler", "typeck.rs")
    block = text.split("for (builtin, effect) in [", 1)[1].split("]", 1)[0]
    out = {}
    for m in re.finditer(r'\("([a-z_]+)",\s*Effect::([A-Za-z]+)\)', block):
        out[m.group(1)] = m.group(2).lower()
    if not out:
        sys.exit("could not read the builtin effect table out of src/rust-compiler/typeck.rs — it moved")
    return out


def commands():
    """The command line, from the usage block in src/rust-compiler/main.rs."""
    text = read("src", "rust-compiler", "main.rs")
    lines = []
    for m in re.finditer(r'eprintln!\("(  burxt [^"]*)"\)', text):
        lines.append(m.group(1))
    # `review` and `mcp-schema` share one eprintln! with an embedded newline, so the tail of that
    # string arrives as its own physical line rather than in a call of its own.
    for m in re.finditer(r'\n(  burxt [a-z-]+ +<[^"\n]*)', text):
        if m.group(1) not in lines:
            lines.append(m.group(1))
    found = []
    for line in lines:
        m = re.match(r"  burxt (\S+)\s+(.*?)\s\s+(.*)$", line)
        if m:
            found.append((m.group(1), m.group(2).strip(), m.group(3).strip()))
        else:
            m = re.match(r"  burxt (\S+)\s\s+(.*)$", line)
            if m:
                found.append((m.group(1), "", m.group(2).strip()))
    names = {c[0] for c in found}
    for must in ("check", "build", "run", "review", "mcp-schema", "lsp"):
        if must not in names:
            sys.exit(
                "the usage block in src/rust-compiler/main.rs no longer lists `%s`, or this scrape stopped "
                "reading it. Fix the scrape rather than dropping the command: two of these are the "
                "most distinctive features in the language." % must
            )
    return found


# ---------------------------------------------------------------------------------------------
# The standard library
# ---------------------------------------------------------------------------------------------

DECL = re.compile(
    r"^(?P<pure>pure\s+)?function\s+"
    r"(?:\(\s*(?P<mut>mutable\s+)?self\s*:\s*(?P<recv>[^)]+?)\s*\)\s*)?"
    r"(?P<name>[a-z_][A-Za-z0-9_]*)\s*(?P<rest>.*)$"
)
TYPE_DECL = re.compile(r"^(?P<kind>class|enum|interface)\s+(?P<name>[A-Z][A-Za-z0-9_]*)")
BANNER = re.compile(r"^//\s*-{2,}\s*(.*?)\s*-{2,}\s*$")


def prose(lines):
    """A `//` run, as markdown. An indented line inside one is an example, and stays one."""
    out = []
    code = []
    for line in lines:
        body = line[2:]
        if body.startswith("    "):
            code.append(body[4:])
            continue
        if code:
            out.append("```burxt\n" + "\n".join(code).rstrip() + "\n```")
            code = []
        out.append(body.strip())
    if code:
        out.append("```burxt\n" + "\n".join(code).rstrip() + "\n```")

    # Blank-separated paragraphs, with the fences kept whole.
    text, para = [], []
    for piece in out:
        if piece.startswith("```"):
            if para:
                text.append(" ".join(para))
                para = []
            text.append(piece)
        elif piece == "":
            if para:
                text.append(" ".join(para))
                para = []
        else:
            para.append(piece)
    if para:
        text.append(" ".join(para))
    return "\n\n".join(t for t in text if t.strip())


def module(name):
    """Every declaration in lib/<name>.bx, with the prose written above it."""
    path = os.path.join("lib", name + ".bx")
    lines = read(path).splitlines()

    # The banner at the top of the file: `// lib/map.bx — a key-value table, in insertion order.`
    title, blurb = name, []
    for i, line in enumerate(lines[:40]):
        m = re.match(r"^//\s*lib/%s\.bx\s*[—-]\s*(.*)$" % re.escape(name), line)
        if m:
            title = m.group(1).strip().rstrip(".")
            for after in lines[i + 1:]:
                if after.startswith("// ===") or not after.startswith("//"):
                    break
                # The banner shows the `use` line as an indented example. This page already renders
                # that line itself, and prose() would turn it into a second, identical fence.
                if re.match(r'^//\s+use\s+"lib/', after):
                    continue
                blurb.append(after)
            break

    symbols = []
    buffer = []
    section = None
    for n, line in enumerate(lines):
        raw = line.rstrip()
        if raw.startswith("// ==="):
            buffer = []
            continue
        b = BANNER.match(raw)
        if b:
            section = b.group(1) or None
            buffer = []
            continue
        if raw.startswith("//"):
            buffer.append(raw)
            continue
        if not raw.strip():
            # Prose separated from a declaration by a blank line is about the section, not the
            # declaration. Attributing it would put a paragraph about tombstones under `count`.
            buffer = []
            continue

        signature = raw.split(" {")[0].rstrip().rstrip("{").rstrip()
        t = TYPE_DECL.match(raw)
        d = DECL.match(raw)
        if t:
            # A one-line `class Map<K, V> { entries: … }` carries its fields in the signature.
            whole = raw.rstrip()
            symbols.append({
                "name": t.group("name"),
                "kind": t.group("kind"),
                "signature": whole if whole.endswith("}") else signature,
                "doc": prose(buffer),
                "section": section,
                "line": n + 1,
            })
        elif d:
            recv = (d.group("recv") or "").strip()
            symbols.append({
                "name": d.group("name"),
                "kind": "method" if recv else "function",
                "receiver": recv or None,
                "mutates": bool(d.group("mut")),
                "signature": signature,
                "doc": prose(buffer),
                "section": section,
                "line": n + 1,
            })
        buffer = []

    if not symbols:
        sys.exit("read no declarations out of %s — the parser needs fixing" % path)
    return {"name": name, "path": path, "title": title, "blurb": prose(blurb), "symbols": symbols}


# ---------------------------------------------------------------------------------------------
# The builtins
#
# `signature` and `answers` are written here; `probe` is what proves them. Every probe is compiled,
# and a failing one stops this script — so a signature on the page is one the compiler accepted.
# `refuses`, where present, is a program whose refusal is quoted verbatim, because a builtin's
# limits are the interesting half and a paraphrase of an error message is how the guide once lied.
# ---------------------------------------------------------------------------------------------

BUILTINS = [
    # ---- eleven that were implemented and never documented, added by the 1.0 scan (roadmap B14).
    # The page claims to be generated from `is_reserved_name`, and nine of these were missing from
    # THAT list too — one omission showing up twice, which is what a single source of truth is for.
    {
        "name": "print_error",
        "signature": "print_error(value)",
        "answers": "nothing",
        "region": False,
        "doc": "Writes one value and a newline to **standard error**. The same statement as `print` "
               "with a different destination, so the per-type formatting cannot fork \u2014 two "
               "statements would mean two formatters, and the first time one learned about a new "
               "type the other would print something else.",
        "probe": 'print_error("something went wrong");\n',
    },
    {
        "name": "bit_and",
        "signature": "bit_and(a: Int, b: Int)",
        "answers": "`Int`",
        "region": False,
        "doc": "Bitwise AND. **Named rather than an operator**, because `a & b == c` means "
               "`a & (b == c)` in C \u2014 a precedence table a reviewer has to remember is the "
               "opposite of what this language is for.",
        "probe": 'print(bit_and(12, 10));\n',
    },
    {
        "name": "bit_or",
        "signature": "bit_or(a: Int, b: Int)",
        "answers": "`Int`",
        "region": False,
        "doc": "Bitwise OR.",
        "probe": 'print(bit_or(12, 10));\n',
    },
    {
        "name": "bit_xor",
        "signature": "bit_xor(a: Int, b: Int)",
        "answers": "`Int`",
        "region": False,
        "doc": "Bitwise XOR.",
        "probe": 'print(bit_xor(12, 10));\n',
    },
    {
        "name": "bit_not",
        "signature": "bit_not(a: Int)",
        "answers": "`Int`",
        "region": False,
        "doc": "Every bit flipped. `bit_not(0)` is `-1`, because an `Int` is signed and there is "
               "nowhere else for the top bit to go.",
        "probe": 'print(bit_not(0));\n',
    },
    {
        "name": "shift_left",
        "signature": "shift_left(x: Int, n: Int)",
        "answers": "`Int`",
        "region": False,
        "doc": "Shifts left by `n`, which must be 0 to 63. Bits shifted past the top are "
               "**discarded** \u2014 the one place in this language where losing information is not "
               "an error, because it is what a shift is for. So it is **not** `x * 2^n`: "
               "multiplication traps on overflow and this does not.",
        "probe": 'print(shift_left(1, 10));\n',
    },
    {
        "name": "shift_right_zeros",
        "signature": "shift_right_zeros(x: Int, n: Int)",
        "answers": "`Int`",
        "region": False,
        "doc": "Shifts right by `n`, filling with zeros \u2014 a logical shift. "
               "`shift_right_zeros(-1, 63)` is `1`. Two right shifts exist because on a negative "
               "value zero-fill and sign-fill give different answers, and one symbol cannot say "
               "which.",
        "probe": 'print(shift_right_zeros(0 - 1, 63));\n',
    },
    {
        "name": "shift_right_sign",
        "signature": "shift_right_sign(x: Int, n: Int)",
        "answers": "`Int`",
        "region": False,
        "doc": "Shifts right by `n`, copying the sign bit \u2014 an arithmetic shift. "
               "`shift_right_sign(-1, 63)` is `-1`, and `shift_right_sign(x, n)` equals "
               "`divide_floor(x, 2^n)`.",
        "probe": 'print(shift_right_sign(0 - 1, 63));\n',
    },
    {
        "name": "c_is_null",
        "signature": "c_is_null(p: CPointer)",
        "answers": "`Bool`",
        "region": False,
        "doc": "Did the C call fail? One of only **two** things that may be done with a `CPointer`. "
               "There is no `==` on one, no arithmetic and no printing \u2014 a pointer is a token "
               "to hand back to C, not a value to reason about.",
        "probe": 'external function strstr(a: String, b: String) -> CPointer;\nprint(c_is_null(strstr(\"ab\", \"b\")));\n',
    },
    {
        "name": "c_string_at",
        "signature": "c_string_at(p: CPointer)",
        "answers": "`String`",
        "region": True,
        "doc": "Copies NUL-terminated bytes from C into a Burxt `String`. **The copy is the wall**: "
               "afterwards Burxt owns the bytes and the pointer is not kept, so who frees it stops "
               "being a question. A null pointer dies here rather than answering `\"\"` \u2014 "
               "unset and empty are different facts.",
        "probe": 'external function strstr(a: String, b: String) -> CPointer;\nprint(c_string_at(strstr(\"hello world\", \"world\")));\n',
    },
    {
        "name": "c_bytes_at",
        "signature": "c_bytes_at(p: CPointer, n: Int)",
        "answers": "`[Int]`",
        "region": True,
        "doc": "Copies `n` bytes from C into a growable array, one byte per element, "
               "zero-extended so `0xFF` arrives as `255` rather than `-1`. The counterpart to "
               "`c_string_at`, and it is what makes OS entropy reachable: `/dev/urandom` is a "
               "character device, so `read_file` measures it and gets nothing. **Where the length "
               "comes from is the pointer wall's one soft edge** \u2014 `n` is your claim, and "
               "nothing in the type can check it. A null pointer and a negative count are refused.",
        "probe": 'external function strstr(a: String, b: String) -> CPointer;\nlet bytes: [Int] = c_bytes_at(strstr(\"hello\", \"llo\"), 3);\nprint(len(bytes));\n',
    },

    {
        "name": "print",
        "signature": "print(value)",
        "answers": "nothing",
        "region": False,
        "doc": "Writes one value and a newline. Takes an `Int`, a `Bool`, a `String` or a "
               "`Decimal<S>`, and an interpolated string goes out piece by piece with nothing "
               "built — which is why printing costs no memory.",
        "probe": 'print("x");\nprint(1);\nprint(true);\nprint($1.50);\n',
    },
    {
        "name": "len",
        "signature": "len(xs) -> Int",
        "answers": "how many elements, or how many BYTES of a `String`",
        "region": False,
        "doc": "On a `String` this counts bytes, not characters. That is deliberate and it is the "
               "same decision `byte_at` makes: the byte-versus-character question is one a program "
               "has to answer, and a name that hid it would answer it wrongly for somebody.",
        "probe": 'let xs: [Int; 3] = [1, 2, 3];\nprint(len(xs));\nprint(len("hello"));\n',
    },
    {
        "name": "byte_at",
        "signature": "byte_at(s, i) -> Int",
        "answers": "the byte at `i`",
        "region": False,
        "doc": "Bounds are always checked. The name says BYTE so that nothing has to guess whether "
               "an index into text means a byte or a character.",
        "probe": 'print(byte_at("hello", 1));\n',
    },
    {
        "name": "byte_as_string",
        "signature": "byte_as_string(n) -> String",
        "answers": "a one-byte `String` holding `n`",
        "region": True,
        "doc": "**The exact inverse of `byte_at`**: `byte_at(byte_as_string(n), 0)` is `n` for every "
               "one of the 256 values. `n` must be 0 to 255 — a literal outside that is refused "
               "when the program is compiled, and anything computed is checked when it runs.\n\n"
               "It is the ONLY way to turn a number into text, and the reason it had to be a builtin "
               "rather than a library function: `substring` of a literal was the only Int-to-String "
               "path there was, and a source file must be valid UTF-8, so a byte above 127 could only "
               "be written down inside a complete multi-byte character. `to_string(233)` is a "
               "different conversion — three digit characters, `\"233\"`.\n\n"
               "**It is also the one builtin that can build a `String` `is_valid_utf8` rejects.** "
               "`byte_as_string(0xC3)` on its own is a UTF-8 lead byte with no continuation after it. "
               "That is what it is FOR — assembling a sequence one byte at a time — but it "
               "means the caller owns the validity of what comes out. For text, use "
               "`from_codepoint` in `lib/string.bx`, which emits a whole character or refuses.\n\n"
               "A zero byte is ORDINARY, not a terminator: a Burxt `String` carries its length in a "
               "header, so `byte_as_string(0)` has length 1 and the full 0..255 range needs no "
               "special case.",
        "probe": 'print(byte_as_string(65));\n'
                 'print(byte_at(byte_as_string(200), 0));\n'
                 'print(byte_as_string(195) + byte_as_string(169));\n',
        "refuses": 'print(byte_as_string(256));\n',
    },
    {
        "name": "substring",
        "signature": "substring(s, from, count) -> String",
        "answers": "`count` bytes of `s`, starting at `from`",
        "region": True,
        "doc": "Builds a new String, so it needs somewhere to put it.",
        "probe": 'print(substring("hello", 1, 3));\n',
    },
    {
        "name": "to_string",
        "signature": "to_string(value) -> String",
        "answers": "the value, written out",
        "region": True,
        "doc": "Takes an `Int`, a `Bool` or a `Decimal<S>`. It shares its formatter with `print`, so "
               "the two can never disagree about what a number looks like. A `Bool` allocates "
               "nothing, because both answers are constants.\n\n"
               "There is no way for a class of yours to have one: `to_string` is a builtin rather "
               "than an interface a type can implement, so a user type has no display form. That "
               "is a real gap rather than a decision.",
        "probe": 'print(to_string(42));\nprint(to_string($19.99));\nprint(to_string(true));\n',
        "refuses": 'let s: String = "already text";\nprint(to_string(s));\n',
    },
    {
        "name": "push",
        "signature": "push(xs, value) -> Int",
        "answers": "the new length",
        "region": True,
        "doc": "Appends to a growable array. The array lives in a region, which is what makes "
               "growing it a bump rather than a reallocation someone has to own.",
        "probe": 'let mutable xs: [Int] = [];\nprint(push(xs, 1));\n',
    },
    {
        "name": "truncate",
        "signature": "truncate(xs, n) -> Int",
        "answers": "the new length",
        "region": False,
        "doc": "Shortens a growable array to `n`. Nothing is freed — the region owns the storage, "
               "and it goes when the region does.",
        "probe": 'let mutable xs: [Int] = [];\npush(xs, 1);\nprint(truncate(xs, 0));\n',
    },
    {
        "name": "read_file",
        "signature": "read_file(path) -> String",
        "answers": "the whole file",
        "region": True,
        "doc": "Reaches the filesystem, so it is registered as `touches files` — a function that "
               "calls it must say so, and one that does not may not call it.",
        "probe": 'function load(path: String) -> String allocates touches files {\n'
                 '    return read_file(path);\n}\n',
    },
    {
        "name": "write_file",
        "signature": "write_file(path, contents) -> Int",
        "answers": "how many bytes went out",
        "region": False,
        "doc": "Replaces the file. Reaches the filesystem, so it carries `touches files`.",
        "probe": 'function save(path: String, text: String) -> Int touches files {\n'
                 '    return write_file(path, text);\n}\n',
    },
    {
        "name": "write_bytes",
        "signature": "write_bytes(path, buffer) -> Int",
        "answers": "how many bytes went out",
        "region": False,
        "doc": "Writes a growable `[Int]` where each element is one byte. For output that is not "
               "text — and a value outside 0–255 is a refusal rather than a truncation.",
        "probe": 'function dump(path: String, bytes: [Int]) -> Int touches files {\n'
                 '    return write_bytes(path, bytes);\n}\n',
    },
    {
        "name": "argument",
        "signature": "argument(n) -> String",
        "answers": "the nth command-line argument",
        "region": False,
        "doc": "Reads the command line, which is `touches input`.",
        "probe": 'function first() -> String touches input {\n    return argument(1);\n}\n',
    },
    {
        "name": "argument_count",
        "signature": "argument_count() -> Int",
        "answers": "how many arguments there are",
        "region": False,
        "doc": "Reads the command line, which is `touches input`.",
        "probe": 'function how_many() -> Int touches input {\n    return argument_count();\n}\n',
    },
    {
        "name": "divide_floor",
        "signature": "divide_floor(a, b) -> Int",
        "answers": "`a / b`, rounded toward negative infinity",
        "region": False,
        "doc": "`Int / Int` is refused, because the two reasonable answers for a negative numerator "
               "disagree and an operator cannot ask which you meant. This is one of them; "
               "`divide_toward_zero` is the other. Dividing by zero stops the program.",
        "probe": 'print(divide_floor(-7, 2));\n',
    },
    {
        "name": "divide_toward_zero",
        "signature": "divide_toward_zero(a, b) -> Int",
        "answers": "`a / b`, rounded toward zero",
        "region": False,
        "doc": "What C and most CPUs do. The other half of the pair `Int / Int` refuses to guess "
               "between.",
        "probe": 'print(divide_toward_zero(-7, 2));\n',
    },
    {
        "name": "remainder",
        "signature": "remainder(a, b) -> Int",
        "answers": "what is left over",
        "region": False,
        "doc": "Keeps the sign of its LEFT operand, like C's `%`. Worth knowing when the result "
               "indexes something: a negative index is a bounds failure, not a wrong answer.",
        "probe": 'print(remainder(7, 2));\n',
    },
    {
        "name": "hash",
        "signature": "hash(key) -> Int",
        "answers": "a non-negative hash",
        "region": False,
        "doc": "Defined on the `Equatable` types — `Int`, `Bool`, `String`, `Decimal<S>` — which is "
               "exactly the set `==` works on. The sign bit is cleared, so it can index a table "
               "through `remainder` without producing a negative index. This is the only compiler "
               "support `lib/map.bx` needs.",
        "probe": 'print(hash("key"));\nprint(hash(7));\n',
    },
    {
        "name": "old",
        "signature": "old(expression)",
        "answers": "what the expression was BEFORE the body ran",
        "region": False,
        "doc": "Legal only inside an `ensures` clause, where it is what lets a postcondition talk "
               "about change rather than only about the answer.\n\n"
               "One limit worth knowing, and it is the compiler's rather than the design's: an "
               "`ensures` on a method that returns a **class** is refused today. A class travels "
               "back through a hidden pointer into the caller's storage, and binding `result` to "
               "that needs care a scalar does not. Return a scalar, or drop the clause.",
        "probe": 'class Counter {\n    n: Int,\n\n'
                 '    function (self) next() -> Int\n'
                 '        ensures result == old(self.n) + 1\n'
                 '    { return self.n + 1; }\n}\n',
        "refuses": 'class Counter {\n    n: Int,\n\n'
                   '    function (self) bumped() -> Counter\n'
                   '        ensures result.n == old(self.n) + 1\n'
                   '    { return Counter { n: self.n + 1 }; }\n}\n',
    },
    {
        "name": "result",
        "signature": "result",
        "answers": "the value being returned",
        "region": False,
        "doc": "A name, not a call, and in scope only inside an `ensures` clause. A declaration that "
               "takes a parameter called `result` and also writes `result` in an `ensures` is "
               "refused for the collision rather than shadowed quietly.",
        "probe": 'function doubled(n: Int) -> Int\n    ensures result == n * 2\n'
                 '{ return n * 2; }\n',
    },
    {
        "name": "exit",
        "signature": "exit(code)",
        "answers": "nothing — the program ends",
        "region": False,
        "doc": "Reserved because the runtime calls libc's `exit` to end a program on a failed "
               "contract or a bounds violation. A program that shadowed it would change what a "
               "failure does.",
        "probe": None,
    },
    {
        "name": "main",
        "signature": "main",
        "answers": "nothing — it is not an entry point",
        "region": False,
        "doc": "Burxt has no entry point: the whole file is the program, and statements at the top "
               "level run in order. So a function called `main` would look like an entry point and "
               "not be one — a trap rather than a crash, which is the kind of thing this language "
               "refuses. The name is reserved so it cannot be set.",
        "probe": None,
    },
]


def compiler(source, work, name="probe", argv=("check",)):
    """Run the compiler on a program, and hand back everything it said.

    The file is named after the builtin rather than `probe.bx`, because the compiler's `-->` line
    ends up on the page and a reader should see `to_string.bx` there rather than the mechanics of
    this script.
    """
    stem = "%s.bx" % name
    path = os.path.join(work, stem)
    with open(path, "w") as f:
        f.write(source)
    done = subprocess.run(
        [BURXT, *argv, stem], cwd=work, capture_output=True, text=True, timeout=60
    )
    text = "\n".join(
        l for l in (done.stdout + done.stderr).splitlines() if not l.startswith("compiled ")
    ).strip()
    return done.returncode, text


def verify(work):
    """Compile a use of every builtin, and capture every refusal the page quotes.

    This is what makes the signatures above trustworthy rather than remembered. It also holds the
    two lists against each other: a name the compiler reserves and this file does not describe is
    an error, so adding a builtin to the language fails here until the reference knows about it.
    """
    described = {b["name"] for b in BUILTINS}
    # `print` and `print_error` are KEYWORDS, so the lexer already makes them unusable as
    # identifiers and `is_reserved_name` has no reason to list them. They are still builtins a
    # reader looks up, so they are described.
    owned = set(reserved()) | {"print", "print_error"}
    unknown = sorted(owned - described)
    if unknown:
        sys.exit(
            "the compiler reserves these names and scripts/site-reference.py does not describe "
            "them: %s\nAdd an entry to BUILTINS — a builtin missing from the reference is a "
            "builtin nobody can look up." % unknown
        )
    stale = sorted(described - owned)
    if stale:
        sys.exit(
            "scripts/site-reference.py describes these and the compiler no longer reserves them: "
            "%s\nThe reference would be documenting a language this repository does not have."
            % stale
        )

    for b in BUILTINS:
        if b["probe"]:
            code, said = compiler(b["probe"], work, b["name"])
            if code != 0:
                sys.exit(
                    "the signature written for `%s` does not compile, so it is wrong:\n\n%s\n%s"
                    % (b["name"], b["probe"], said)
                )
        if b.get("refuses"):
            code, said = compiler(b["refuses"], work, b["name"])
            if code == 0:
                sys.exit(
                    "`%s` was expected to refuse this and did not — the page would claim a limit "
                    "the compiler does not have:\n\n%s" % (b["name"], b["refuses"])
                )
            b["refusal"] = said


# ---------------------------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------------------------

FRONT = "---\nlayout: doc\ntitle: %s\nsection: reference\ndescription: %s\n---\n\n"

# The tables that are a decision rather than a scrape. Operators, shorthands and runtime failures
# came across from the hand-written page they replace; they describe grammar, which does not have a
# table in the compiler to read.
OPERATORS = """
| Operator | On | Notes |
|---|---|---|
| `+` `-` | Int, Decimal of the SAME scale, String (`+` only) | Scales must match. A rounding contract on one side is carried into the result; two different contracts are refused |
| `*` | Int, Decimal × Int, Decimal × Decimal | Mixed Decimal scales need a rounding contract |
| `/` | Decimal only | Always needs a rounding contract. `Int / Int` is refused — use `divide_floor` or `divide_toward_zero` |
| `==` `!=` | Any two values of the same type | One equality, no coercion. Strings compare by bytes |
| `<` `<=` `>` `>=` | Int, Decimal | Same type both sides. On String it is refused |
| `&&` `\\|\\|` | Bool | Short-circuit: the right side runs only if it is needed |
| `!` | Bool | |
| unary `-` | Int, Decimal | Checked, like every other arithmetic |
| `+=` `-=` `*=` | Anything the long form allows | `x += e` IS `x = x + e` by the time it is checked. Works on a name, a field and an array element. There is deliberately no `++` |
| `?` | `Result<T, E>` | `f(x)?` returns the failure unchanged, or unwraps the success |
"""

SHORTHANDS = """
| Written | Means |
|---|---|
| `$19.99` | `19.99` as a `Decimal<2>`. The `$` is documentation, not arithmetic |
| `8.25%` | `0.0825` as a `Decimal<4>` — a percent is two scales finer than the number it is written as |
| `"total: {amount}"` | `"total: " + to_string(amount)` — and inside a `print`, the pieces go out in order with nothing built |
| `x += e` | `x = x + e`. Also `-=` and `*=`, on a name, a field, or `xs[i]` |
| `P { x, y }` | `P { x: x, y: y }` — a field taking a variable of the same name |
| `f();` | a call kept for its effect, with no binding |
| `function (self) m()` | `function (self: Type) m()`, inside a block whose header already said which type |
| `P { x: 1, }` | a trailing comma, anywhere a list is written, so adding an item is a one-line diff |
| `let x = e;` | `let x: T = e;` where `T` is `e`'s type. Arrays are the exception — a literal does not say fixed or growable |
| `for x in xs { }` | `let mutable i = 0; while i < len(xs) { let x = xs[i]; … }` — `xs` must be a name or a field path |
| `for i in 0..n { }` | `let mutable i = 0; while i < n { … }` — the end is **exclusive**, `i` is immutable, and both bounds are Ints evaluated once. There is no `..=`, and a range is not a value |
| `f(x)?` | `match f(x) { Error(e) => return Error(e), Ok(v) => v }` — the failure variant found by name, never converted |
| `Int [> 0, <= n]` | `requires` clauses written on the value instead of under the signature |
"""

TYPES = """
| Type | What it is |
|---|---|
| `Int` | Signed 64-bit. **Traps** on overflow, never wraps |
| `Bool` | `true` / `false`. No coercion to or from anything |
| `String` | Bytes, NUL-terminated. `len` counts bytes |
| `Decimal<S>` | An integer scaled by `10^S`, exact. `S` up to 18 |
| `Decimal<S, R>` | The same, carrying a rounding contract: `RoundHalfEven` or `RoundHalfUp` |
| `[T; N]` | Fixed array. The length is part of the type. Bounds always checked |
| `[T]` | Growable array. Lives in a region. Bounds always checked |
| `dynamic Named` | An interface object: a value plus the interface's method table |
| `CInt`, `CDouble` | C's widths. Only in an `external function` signature |
| `i32`, `u8`, `u32`, `u64` | Sized C integers, boundary-only. A value that does not fit **traps** at the call rather than wrapping. `u64` is checked against `Int`'s signed maximum, because Burxt has no wider integer to receive the top half |
"""

# What a well-typed program can still do. These are not compile errors, and the difference is the
# thing the site keeps having to explain: an overflow is a program that STOPS, not one that is
# refused.
FAILURES = """
| What happens | When |
|---|---|
| `arithmetic overflow — the exact result no longer fits in the value range` | `+` `-` `*` on an `Int` or a `Decimal` past its range |
| an index out of range | `xs[i]` outside `0 .. len(xs) - 1` |
| a broken precondition, quoted back with the clause that failed | a `requires` that does not hold at a call |
| a broken postcondition | an `ensures` that does not hold at a return |
| a `decreases` measure that did not decrease | a recursion that would not have ended |
| dividing by zero | `divide_floor`, `divide_toward_zero`, `remainder` |
| `cannot cross as a C double exactly` | a value going out through `CDouble` that a double cannot hold |

Every one of them ends the program, and every one names itself. Nothing here is a warning, and
nothing continues with a wrong value.
"""

CONTEXTUAL = [
    ("allocates", "This function builds values in its CALLER's region. Optional and inferred since "
                  "v0.0.142; writing it is still legal and still checked."),
    ("requires", "A precondition. Checked, and it names itself when it fails."),
    ("ensures", "A postcondition. `result` and `old(...)` are in scope inside one."),
    ("decreases", "A measure that must fall on every recursive call, so the recursion ends."),
    ("touches", "What the function may reach: `files`, `commands`, `clock`, `input`, `network`, "
                "`model`. It travels up the call chain."),
    ("scaled", "In `as scaled`, at the C boundary — the only conversion that moves a Decimal "
               "across it."),
    ("it", "The subject of a contract bracket: `Int [> 0, <= it * 2]`. Special ONLY inside a "
           "bracket."),
]


def anchor(name):
    """The id a heading will carry — and it is WRITTEN OUT, not guessed at.

    kramdown's own rule deletes underscores rather than turning them into hyphens, so the heading
    `to_string` gets the id `tostring`. Every link on these pages was pointing at `to-string`, which
    exists nowhere: a reader clicking `to_string` in the table of contents would have arrived at the
    top of the page, and search would have done the same. It looks like nothing going wrong, because
    the page does load.

    So the generated pages state their ids with an inline attribute list — `{: #to-string}` — and
    these are those ids. Nothing here depends on reproducing kramdown's algorithm.
    """
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def heading(level, text, ident):
    """A heading that CARRIES its id, so the anchor is a fact rather than a prediction."""
    return "%s %s\n{: #%s}\n" % ("#" * level, text, ident)


def plain(text):
    """A heading as a search result should read it: the words, not the markdown."""
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.replace("`", "")
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def signature_block(sig):
    return "```burxt\n%s\n```" % sig


def render_index(kw, ren, cmds):
    out = [FRONT % ("Reference", "Every keyword, builtin, operator and standard-library function — "
                                 "read out of the compiler rather than from memory.")]
    out.append("# Reference\n")
    out.append(
        "Everything the language has. **Read out of the compiler**, not from memory: the keyword "
        "table below comes from `src/rust-compiler/lexer.rs`, the reserved names from `src/rust-compiler/typeck.rs`, the "
        "commands from `src/rust-compiler/main.rs`, and every standard-library entry from the `//` prose written "
        "above the declaration itself. `scripts/site-reference.py` regenerates these pages and a "
        "test diffs them, so this cannot fall behind the language again — which it had: the page "
        "this replaces still listed `record`, a keyword renamed eleven versions earlier.\n"
    )
    out.append("<ul class=\"pages\">")
    out.append('<li><a href="builtins.html"><span>Builtins</span> '
               '<span class="what">%d calls the language owns, and what each needs</span></a></li>'
               % len(BUILTINS))
    out.append('<li><a href="cli.html"><span>The command line</span> '
               '<span class="what">%d commands, including <code>review</code> and '
               '<code>mcp-schema</code></span></a></li>' % len(cmds))
    for name in MODULES:
        out.append('<li><a href="%s.html"><span><code>lib/%s.bx</code></span> '
                   '<span class="what">%s</span></a></li>' % (name, name, MODULE_TITLES[name]))
    out.append("</ul>\n")

    out.append("## Keywords\n")
    out.append("The %d words the lexer knows. Every one of them is the word it means: "
               "`function`, not `fn`; `mutable`, not `mut`.\n" % len(kw))
    rows = ["| | | | |", "|---|---|---|---|"]
    cells = ["`%s`" % w for w in kw]
    for i in range(0, len(cells), 4):
        chunk = cells[i:i + 4] + [""] * (4 - len(cells[i:i + 4]))
        rows.append("| " + " | ".join(chunk) + " |")
    out.append("\n".join(rows) + "\n")

    out.append("## Contextual markers\n")
    out.append("Recognised only where they appear — on a signature, inside a clause — so a variable "
               "may still be called `ensures` anywhere else.\n")
    rows = ["| Marker | What it says |", "|---|---|"]
    for name, what in CONTEXTUAL:
        rows.append("| `%s` | %s |" % (name, what))
    out.append("\n".join(rows) + "\n")

    out.append("## Spellings that do not compile\n")
    out.append("Reserved so the compiler can name the replacement rather than say "
               "*unexpected identifier*. Each of these is an error that tells you the word to "
               "write instead.\n")
    rows = ["| Written | Burxt spells it |", "|---|---|"]
    for old, new in ren:
        rows.append("| `%s` | `%s` |" % (old, new))
    out.append("\n".join(rows) + "\n")

    out.append("## Types\n" + TYPES)
    out.append("## Operators\n" + OPERATORS)
    out.append("## Shorthands\n")
    out.append("The whole list. Burxt has few on purpose, and each is sugar over something it "
               "already means rather than a second way to mean it.\n" + SHORTHANDS)
    out.append("## What stops a running program\n" + FAILURES)

    out.append("## Not present, each for a reason\n")
    out.append(
        "Block comments (`/* … */`) — line comments only, so there is no nesting rule to get "
        "wrong. Multi-line string literals — a literal spanning lines makes its own indentation "
        "part of the data, which is the one thing that surprises everybody about them; use `\\n` "
        "and `+`. `for i in 0..n` — a range is a second construct, and `while i < n` says it. "
        "`for x in text` — a String is bytes, and `byte_at` says BYTE so the byte-versus-character "
        "question cannot hide. `x++` — an expression with a side effect. `a ? b : c` — `if` as an "
        "expression would make it redundant. Arrow functions — they are closures, and captured "
        "state needs an owner.\n"
    )
    return "\n".join(out) + "\n"


def render_builtins(effects):
    out = [FRONT % ("Builtins", "Every call the language owns: what it answers, whether it "
                                "allocates, and what it refuses.")]
    out.append("# Builtins\n")
    out.append(
        "The names a program may not declare, because the language already means something by "
        "them. The list comes from `is_reserved_name` in `src/rust-compiler/typeck.rs`; every signature below "
        "was **compiled** while this page was generated, so none of them is a signature the "
        "compiler would reject.\n"
    )
    rows = ["| Call | Answers | Allocates? | Reaches |", "|---|---|---|---|"]
    for b in BUILTINS:
        eff = effects.get(b["name"])
        rows.append("| [`%s`](#%s) | %s | %s | %s |" % (
            b["name"], anchor(b["name"]), b["answers"],
            "**yes**" if b["region"] else "no",
            "`touches %s`" % eff if eff else "—",
        ))
    out.append("\n".join(rows) + "\n")
    out.append(
        "*Allocates* means the call builds something, and a value has to be built somewhere. **It "
        "does not mean you write `region`.** Since v0.0.146 a program has one from the moment it "
        "starts and `allocates` is inferred, so every signature on this page compiles with no "
        "`region` in sight — the probes that verified them have none. You reach for `region` to "
        "release EARLY, around a loop body or a request, which is the whole of keeping a long-"
        "running program's memory flat. See [Memory](../guide/04-memory.html).\n"
    )

    for b in BUILTINS:
        out.append(heading(2, "`%s`" % b["name"], anchor(b["name"])))
        out.append(signature_block(b["signature"]))
        out.append("")
        out.append(b["doc"] + "\n")
        facts = []
        facts.append("**Answers** %s." % b["answers"])
        facts.append("**Allocates:** %s." % ("yes" if b["region"] else "no"))
        if effects.get(b["name"]):
            facts.append("**Carries** `touches %s`, so a caller must declare it."
                         % effects[b["name"]])
        out.append(" ".join(facts) + "\n")
        if b.get("refusal"):
            out.append("It refuses this:\n")
            out.append("```burxt\n%s```\n" % b["refuses"])
            out.append("```\n%s\n```\n" % b["refusal"])
    return "\n".join(out) + "\n"


def render_cli(cmds):
    out = [FRONT % ("The command line", "Every burxt command, including review and mcp-schema.")]
    out.append("# The command line\n")
    out.append(
        "Read out of the usage block in `src/rust-compiler/main.rs`, so this cannot list a command the compiler "
        "does not have. Two of them exist nowhere else in programming: `burxt review`, which "
        "answers what a change did to what a program **promises**, and `burxt mcp-schema`, which "
        "derives an MCP tool schema from the preconditions so the two cannot drift. Both are "
        "explained in [Tools and agents](../guide/12-tools-and-agents.html).\n"
    )
    rows = ["| Command | Takes | What it does |", "|---|---|---|"]
    for name, takes, what in cmds:
        rows.append("| `burxt %s` | %s | %s |" % (name, "`%s`" % takes if takes else "—", what))
    out.append("\n".join(rows) + "\n")
    out.append(
        "Arguments after the source file go to the linker unchanged, so `burxt run pay.bx cside.o "
        "-lm` links the C you call. `-o <path>` says where the executable goes.\n"
    )
    return "\n".join(out) + "\n"


def sentence(text):
    """A banner line like `absence, made explicit` as a sentence."""
    text = text.strip().rstrip(".")
    if not text:
        return ""
    return text[0].upper() + text[1:] + "."


def render_module(mod):
    out = [FRONT % ("lib/%s.bx" % mod["name"], sentence(mod["title"]))]
    out.append("# `lib/%s.bx`\n" % mod["name"])
    out.append(sentence(mod["title"]) + "\n")
    out.append("```burxt\nuse \"lib/%s.bx\";\n```\n" % mod["name"])
    if mod["blurb"]:
        out.append(mod["blurb"] + "\n")

    functions = [s for s in mod["symbols"] if s["kind"] == "function"]
    methods = [s for s in mod["symbols"] if s["kind"] == "method"]
    types = [s for s in mod["symbols"] if s["kind"] in ("class", "enum", "interface")]

    out.append(heading(2, "What is in it", "what-is-in-it"))
    rows = ["| Name | Kind | What it answers |", "|---|---|---|"]
    for s in types + functions + methods:
        first = (s["doc"].split("\n\n")[0] if s["doc"] else "").strip()
        if first.startswith("```"):
            first = ""
        rows.append("| [`%s`](#%s) | %s | %s |" % (
            s["name"], anchor(s["name"]),
            "method on `%s`" % s["receiver"].split("<")[0] if s["kind"] == "method" else s["kind"],
            first[:120] or "—",
        ))
    out.append("\n".join(rows) + "\n")

    for label, group in (("Types", types), ("Functions", functions), ("Methods", methods)):
        if not group:
            continue
        out.append(heading(2, label, anchor(label)))
        for s in group:
            out.append(heading(3, "`%s`" % s["name"], anchor(s["name"])))
            out.append(signature_block(s["signature"]))
            out.append("")
            if s["doc"]:
                out.append(s["doc"] + "\n")
            if s["kind"] == "method" and s["mutates"]:
                out.append("Takes `mutable self`, so it changes the value it is called on.\n")
            out.append("[Source](%s/%s#L%d)\n" % (GH, mod["path"], s["line"]))
    return "\n".join(out) + "\n"


MODULE_TITLES = {}


def build():
    kw, ren, cmds = keywords(), renamed(), commands()
    effects = builtin_effects()

    work = tempfile.mkdtemp(prefix="burxt-reference-")
    # `use "lib/…"` resolves relative to the file, so the library has to travel with the probes.
    try:
        os.symlink(os.path.join(ROOT, "lib"), os.path.join(work, "lib"))
    except OSError:
        pass
    verify(work)

    mods = [module(name) for name in MODULES]
    for m in mods:
        MODULE_TITLES[m["name"]] = m["title"]

    pages = {
        "index.md": None,           # rendered last: its list needs MODULE_TITLES
        "builtins.md": render_builtins(effects),
        "cli.md": render_cli(cmds),
    }
    for m in mods:
        pages["%s.md" % m["name"]] = render_module(m)
    pages["index.md"] = render_index(kw, ren, cmds)

    # ---- the search index -------------------------------------------------------------------
    #
    # One row per thing anyone would type. `to_str` has to reach `to_string`, which is the specific
    # complaint this whole page set answers.
    items = []
    for b in BUILTINS:
        items.append({
            "name": b["name"], "kind": "builtin",
            "url": "/reference/builtins.html#%s" % anchor(b["name"]),
            "where": b["signature"], "text": b["answers"],
        })
    for name, takes, what in cmds:
        items.append({
            "name": "burxt %s" % name, "kind": "command",
            "url": "/reference/cli.html", "where": what, "text": takes,
        })
    for m in mods:
        for s in m["symbols"]:
            items.append({
                "name": s["name"],
                "kind": "method" if s["kind"] == "method" else s["kind"],
                "url": "/reference/%s.html#%s" % (m["name"], anchor(s["name"])),
                "where": s["signature"],
                "text": "lib/%s.bx" % m["name"],
            })
    for w in kw:
        items.append({
            "name": w, "kind": "keyword", "url": "/reference/#keywords",
            "where": "keyword", "text": "",
        })
    for old, new in ren:
        items.append({
            "name": old, "kind": "refused", "url": "/reference/#spellings-that-do-not-compile",
            "where": "Burxt spells this `%s`" % new, "text": "",
        })
    for name, what in CONTEXTUAL:
        items.append({
            "name": name, "kind": "marker", "url": "/reference/#contextual-markers",
            "where": what[:90], "text": "",
        })
    # Every guide heading, so search reaches the prose too. The ids come from the sidebar
    # generator's `headings`, so a search hit and a sidebar entry always point at the same place.
    guide = os.path.join(ROOT, "docs", "guide")
    for page in sorted(os.listdir(guide)):
        if not re.match(r"^\d\d-.*\.md$", page):
            continue
        path = os.path.join(guide, page)
        title = plain(nav.title_of(path))
        for head, ident in nav.headings(path):
            items.append({
                "name": plain(head), "kind": "guide",
                "url": "/guide/%s.html#%s" % (page[:-3], ident),
                "where": title, "text": "",
            })
    return pages, items


def main():
    if not os.path.exists(BURXT):
        sys.exit("build the compiler first: cargo build --release  (or set BURXT=<path>)")
    pages, items = build()
    index = json.dumps(items, indent=1, sort_keys=True) + "\n"

    if "--check" in sys.argv:
        bad = []
        for name, text in pages.items():
            path = os.path.join(OUT, name)
            on_disk = open(path).read() if os.path.exists(path) else ""
            if on_disk != text:
                bad.append("docs/reference/%s" % name)
        on_disk = open(SEARCH).read() if os.path.exists(SEARCH) else ""
        if on_disk != index:
            bad.append("docs/assets/search.json")
        if bad:
            sys.exit("out of date: %s — run: python3 scripts/site-reference.py" % ", ".join(bad))
        print("docs/reference/ is current (%d pages, %d search entries)" % (len(pages), len(items)))
        return

    os.makedirs(OUT, exist_ok=True)
    for name, text in pages.items():
        with open(os.path.join(OUT, name), "w") as f:
            f.write(text)
    with open(SEARCH, "w") as f:
        f.write(index)
    print("wrote docs/reference/ (%d pages) and docs/assets/search.json (%d entries)"
          % (len(pages), len(items)))


if __name__ == "__main__":
    main()
